### ISSUE TITLE
Patches

### ISSUE THREAD

**Issue by bibi21000** [maartendamen/py-openzwave#5]
Hi,
I've made some patches to build py-openzwave with the last release of openzwave.
Should I publish them here or fork this repository ?

**Comment by maartendamen** [comment]
Hi,

Please fork the repository and send a pull request. Thanks a lot for contributing!

Best regards,
Maarten

**Comment by bibi21000** [comment]
I don't know how admin a git repository. As I am more familar with mercurial, I think I will use google code to fork.
Actually, changes are conséquent : remove openzwave directory, a small script to install and some documentation generation. There is also debian scripts to make a package. So, I don
There is no Licence information in py-openzave. So I suppose it's under GPL v3
Should I let your name in the authors or not ? Should I add a copyright ? 
Should I put your email address ? What it is ?
And last question, should I use the same name or not ?
Best regards,
Sebastien (bibi)

**Comment by maartendamen** [comment]
Have you seen my no-fork branch? It doesn't contain the openzwave directory. I would prefer to keep all the changes to the project on one location (Github). I will mention your contribution in the readme. Please drop me a mail on m.damen AT gmail.com so we can work something out regarding the changes. Thanks!
